### ISSUE TITLE
Add Phaser containers support in scene editor.

### ISSUE THREAD

**Issue by RANUX** [PhaserEditor2D/PhaserEditor#100]
Hi!
Missing nice feature to group sprites in containers on scene (PhaserEditor v2)!
Thanks!

**Comment by PhaserEditor2D** [comment]
Yes, we are evaluating when to start supporting containers, because the Phaser team will rework the whole thing in Phaser, they plan to allow nested containers, even, nested objects. But I see this can take a time to be done, yet, they don't finish the v3.16. We are going to release v2.0.1 to support Phaser 3.16 and after that, we are going to start working on containers.

You can read here, in the [2019 roadmap](http://phaser.io/news/2019/01/phaser-in-2018-and-beyond), what they say about containers:

**Before anything like that can happen I need to release 3.16 (with the long-awaited Scale Manager), re-work how Containers are supported in the core, and get the list of issues down to a manageable number.**

And you can read here too:

https://github.com/photonstorm/phaser/issues/3852

"Containers will be removed and fully recoded in 3.14. I'm fed up with their limitations and the issues the current implementation has. They will remain untouched (and un bug-fixed) until then."

It did not happen in 3.14.

**Comment by PhaserEditor2D** [comment]
This is not going to happing in v2. We are implementing a new web-based IDE for Phaser 3. This new version has support for containers.
