### ISSUE TITLE
[v2] Default preferences are not saved

### ISSUE THREAD

**Issue by RiCoTeRoX** [PhaserEditor2D/PhaserEditor#105]
**paid user**

## IDE 2.0 - phaser 3.15
* Operating system: MacOs Mojave 10.14.1

## Description
Preferences from startup lancher don's save it.
- workspace directory
- any custom settings

second time i've launched, it stop responding. I've to kill it from monitor panel.

i already run the SetExecPermissions.sh, i also did manually with 775 and 755.

pd: when i run with sudo 
sudo /Applications/PhaserEditor2D/PhaserEditor2D.app/Contents/MacOS/PhaserEditor2D

everything works perfectly :/

**Comment by PhaserEditor2D** [comment]
Hi @RiCoTeRoX 

I just can answer this now, I was in travel to the GGJ.

If it works with admin privileges maybe it is because it is trying to write data in a protected folder. Please, try unzipping the "installation" in the desktop or any other "user" folder, and tell me if it works (the editor is a portable application).

**Comment by RiCoTeRoX** [comment]
Hello and welcome again!
I tried to delete all the related phasereditor files and then simply unzipped into the / downloads folder and copied to / Applications and it works fine.
But I did not run any .sh script like I did before. maybe was that.

**Comment by PhaserEditor2D** [comment]
I am happy it is working now. The `.sh` scripts are optional.
