### ISSUE TITLE
export class option for auto-generated typescript file for canvas

### ISSUE THREAD

**Issue by stzseungwon** [PhaserEditor2D/PhaserEditor#75]
I made an nested kind of group canvas and I need to access those class in parent class.
So 'export' option for class(in this case, group) is appreciated.

If there is any workaround for solving this problem, please let me know.

Thanks!

**Comment by stzseungwon** [comment]
And I just found out when there are 'import' in the header of file, then other class won't recognize this class.

foo.ts

`//import { GameConfig } from '../../../js/GameEngine/GameConfig';//if commented, this 'foo' class recognized by other class but when uncommented it won't
// -- user code here --

/* --- start generated code --- */

// Generated by  1.5.0 (Phaser v2.6.2)`

**Comment by PhaserEditor2D** [comment]
> I made an nested kind of group canvas and I need to access those class in parent class.

I do not understand very well. Do you mean you did an X group prefab and you want to access the X class from another file?

> And I just found out when there are 'import' in the header of file, then other class won't recognize this class.

When you say `then other class won't recognize this` do you mean the TS compiler shows an error or the compiled JS code does not work in execution time?

Modules are a bit frustrating in TS if you are targeting JS5, because JS5 does not support modules.

You can take a look to this thread:

https://stackoverflow.com/questions/43472778/typescript-exports-is-not-defined

And another user of Phaser Editor experienced a similar problem:

https://github.com/PhaserEditor2D/PhaserEditor/issues/67

https://github.com/PhaserEditor2D/PhaserEditor/issues/70

**Comment by PhaserEditor2D** [comment]
I think it is all about the TypeScript rules. Do you have any particular request to Phaser Editor? You can add import and export statements at the beginning or end of the files.

**Comment by PhaserEditor2D** [comment]
I close this. If you have any finding please reopen.
